// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/analytics" | "/create" | "/festivals" | "/gallery" | "/instagram-ai" | "/instagram-posts" | "/login" | "/schedule" | "/settings"
type AppRouteHandlerRoutes = "/api/canva/autofill" | "/api/canva/oauth/callback" | "/api/canva/oauth/session" | "/api/canva/oauth/start" | "/api/canva/oauth/status" | "/api/canva/templates" | "/api/cardnews/image-proxy" | "/api/cardnews/item" | "/api/cardnews/list" | "/api/cardnews/publish" | "/api/cardnews/slide-image" | "/api/festivals" | "/api/festivals/naver-update" | "/api/festivals/research" | "/api/generate-caption" | "/api/generate-slides" | "/api/meta/accounts" | "/api/meta/accounts/active" | "/api/meta/insights" | "/api/meta/oauth/callback" | "/api/meta/oauth/session" | "/api/meta/oauth/start" | "/api/meta/oauth/status" | "/api/meta/pages" | "/api/meta/posts" | "/api/meta/publishing" | "/api/meta/publishing/dispatch" | "/api/meta/selection" | "/api/stats" | "/api/suggest-angles"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/analytics": {}
  "/api/canva/autofill": {}
  "/api/canva/oauth/callback": {}
  "/api/canva/oauth/session": {}
  "/api/canva/oauth/start": {}
  "/api/canva/oauth/status": {}
  "/api/canva/templates": {}
  "/api/cardnews/image-proxy": {}
  "/api/cardnews/item": {}
  "/api/cardnews/list": {}
  "/api/cardnews/publish": {}
  "/api/cardnews/slide-image": {}
  "/api/festivals": {}
  "/api/festivals/naver-update": {}
  "/api/festivals/research": {}
  "/api/generate-caption": {}
  "/api/generate-slides": {}
  "/api/meta/accounts": {}
  "/api/meta/accounts/active": {}
  "/api/meta/insights": {}
  "/api/meta/oauth/callback": {}
  "/api/meta/oauth/session": {}
  "/api/meta/oauth/start": {}
  "/api/meta/oauth/status": {}
  "/api/meta/pages": {}
  "/api/meta/posts": {}
  "/api/meta/publishing": {}
  "/api/meta/publishing/dispatch": {}
  "/api/meta/selection": {}
  "/api/stats": {}
  "/api/suggest-angles": {}
  "/create": {}
  "/festivals": {}
  "/gallery": {}
  "/instagram-ai": {}
  "/instagram-posts": {}
  "/login": {}
  "/schedule": {}
  "/settings": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
