// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/create">> = Specific
  const handler = {} as typeof import("../../src/app/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/festivals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/festivals">> = Specific
  const handler = {} as typeof import("../../src/app/festivals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/gallery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gallery">> = Specific
  const handler = {} as typeof import("../../src/app/gallery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/instagram-ai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instagram-ai">> = Specific
  const handler = {} as typeof import("../../src/app/instagram-ai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/instagram-posts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/instagram-posts">> = Specific
  const handler = {} as typeof import("../../src/app/instagram-posts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/schedule">> = Specific
  const handler = {} as typeof import("../../src/app/schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/canva/autofill/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/canva/autofill">> = Specific
  const handler = {} as typeof import("../../src/app/api/canva/autofill/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/canva/oauth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/canva/oauth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/canva/oauth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/canva/oauth/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/canva/oauth/session">> = Specific
  const handler = {} as typeof import("../../src/app/api/canva/oauth/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/canva/oauth/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/canva/oauth/start">> = Specific
  const handler = {} as typeof import("../../src/app/api/canva/oauth/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/canva/oauth/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/canva/oauth/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/canva/oauth/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/canva/templates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/canva/templates">> = Specific
  const handler = {} as typeof import("../../src/app/api/canva/templates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cardnews/image-proxy/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cardnews/image-proxy">> = Specific
  const handler = {} as typeof import("../../src/app/api/cardnews/image-proxy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cardnews/item/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cardnews/item">> = Specific
  const handler = {} as typeof import("../../src/app/api/cardnews/item/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cardnews/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cardnews/list">> = Specific
  const handler = {} as typeof import("../../src/app/api/cardnews/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cardnews/publish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cardnews/publish">> = Specific
  const handler = {} as typeof import("../../src/app/api/cardnews/publish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cardnews/slide-image/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cardnews/slide-image">> = Specific
  const handler = {} as typeof import("../../src/app/api/cardnews/slide-image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/festivals/naver-update/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/festivals/naver-update">> = Specific
  const handler = {} as typeof import("../../src/app/api/festivals/naver-update/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/festivals/research/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/festivals/research">> = Specific
  const handler = {} as typeof import("../../src/app/api/festivals/research/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/festivals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/festivals">> = Specific
  const handler = {} as typeof import("../../src/app/api/festivals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/generate-caption/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/generate-caption">> = Specific
  const handler = {} as typeof import("../../src/app/api/generate-caption/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/generate-slides/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/generate-slides">> = Specific
  const handler = {} as typeof import("../../src/app/api/generate-slides/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/meta/accounts/active/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meta/accounts/active">> = Specific
  const handler = {} as typeof import("../../src/app/api/meta/accounts/active/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/meta/accounts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meta/accounts">> = Specific
  const handler = {} as typeof import("../../src/app/api/meta/accounts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/meta/insights/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meta/insights">> = Specific
  const handler = {} as typeof import("../../src/app/api/meta/insights/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/meta/oauth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meta/oauth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/meta/oauth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/meta/oauth/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meta/oauth/session">> = Specific
  const handler = {} as typeof import("../../src/app/api/meta/oauth/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/meta/oauth/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meta/oauth/start">> = Specific
  const handler = {} as typeof import("../../src/app/api/meta/oauth/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/meta/oauth/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meta/oauth/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/meta/oauth/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/meta/pages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meta/pages">> = Specific
  const handler = {} as typeof import("../../src/app/api/meta/pages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/meta/posts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meta/posts">> = Specific
  const handler = {} as typeof import("../../src/app/api/meta/posts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/meta/publishing/dispatch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meta/publishing/dispatch">> = Specific
  const handler = {} as typeof import("../../src/app/api/meta/publishing/dispatch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/meta/publishing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meta/publishing">> = Specific
  const handler = {} as typeof import("../../src/app/api/meta/publishing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/meta/selection/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meta/selection">> = Specific
  const handler = {} as typeof import("../../src/app/api/meta/selection/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/suggest-angles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/suggest-angles">> = Specific
  const handler = {} as typeof import("../../src/app/api/suggest-angles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
